
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int tuple = 16;
  public static final int bool = 15;
  public static final int lesseqrel = 28;
  public static final int function = 2;
  public static final int input = 17;
  public static final int equalrel = 23;
  public static final int main = 11;
  public static final int xnor = 35;
  public static final int minop = 20;
  public static final int elset = 7;
  public static final int greatereqrel = 27;
  public static final int comma = 37;
  public static final int mulop = 21;
  public static final int truet = 12;
  public static final int ift = 6;
  public static final int whilet = 9;
  public static final int returnt = 5;
  public static final int equal = 18;
  public static final int constt = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int sumop = 19;
  public static final int notequalrel = 24;
  public static final int or = 30;
  public static final int fort = 8;
  public static final int closep = 39;
  public static final int integer = 14;
  public static final int divop = 22;
  public static final int id = 42;
  public static final int xor = 32;
  public static final int println = 4;
  public static final int closeb = 41;
  public static final int and = 29;
  public static final int not = 31;
  public static final int openp = 38;
  public static final int greaterrel = 25;
  public static final int nor = 34;
  public static final int lessrel = 26;
  public static final int print = 3;
  public static final int falset = 13;
  public static final int semicolon = 36;
  public static final int dot = 43;
  public static final int openb = 40;
  public static final int nand = 33;
  public static final int number = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "function",
  "print",
  "println",
  "returnt",
  "ift",
  "elset",
  "fort",
  "whilet",
  "constt",
  "main",
  "truet",
  "falset",
  "integer",
  "bool",
  "tuple",
  "input",
  "equal",
  "sumop",
  "minop",
  "mulop",
  "divop",
  "equalrel",
  "notequalrel",
  "greaterrel",
  "lessrel",
  "greatereqrel",
  "lesseqrel",
  "and",
  "or",
  "not",
  "xor",
  "nand",
  "nor",
  "xnor",
  "semicolon",
  "comma",
  "openp",
  "closep",
  "openb",
  "closeb",
  "id",
  "dot",
  "number"
  };
}

